### ISSUE TITLE
Error when specifying number of columns

### ISSUE THREAD

**Issue by Jonty** [tuna-f1sh/node-flipdot#1]
I've not actually managed to get my display working yet, however when specifying the number of columns `flipdot` crashes.

```
(sandbox) jonty@towel:~/sandbox/Hanover_Flipdot (master)$ node /usr/local/bin/flipdot -a 1 -p /dev/tty.wchusbserial1410 -s "Hi" -c 20 -r 14
/usr/local/lib/node_modules/flipdot-display/flipdot.js:480
      this._queue.push(data.slice(i,this.ldata+i));
                 ^

TypeError: Cannot read property 'push' of undefined
    at FlipDot.load (/usr/local/lib/node_modules/flipdot-display/flipdot.js:480:18)
    at FlipDot.writeText (/usr/local/lib/node_modules/flipdot-display/flipdot.js:291:18)
    at new FlipDot (/usr/local/lib/node_modules/flipdot-display/flipdot.js:85:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/flipdot-display/bin/term.js:17:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

Unrelated question you can perhaps help with: If the header has an incorrect display size, will it accept the packet anyway? My display won't respond at all!

**Comment by tuna-f1sh** [comment]
I've pushed a fix for this after quickly testing. It was due to queue initialising after using `writeText('null')` during the constructor. Using a display with such a short number of columns meant it was trying to queue that string whereas I've tested with displays which can fit it in one write. You might need to use `clear()` to prevent the queue loading when you write.

I don't think the display will accept the wrong size header, no. Other things to check if not responding is the hardware address and RS485 differential channels the right way around.
